//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace htmlInterpreter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("htmlInterpreter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html,s
        ///head,s
        ///body,s
        ///footer,s
        ///div,s
        ///h1,s
        ///h2,s
        ///h3,s
        ///h4,s
        ///h5,s
        ///p,s
        ///style,s
        ///class,s.
        /// </summary>
        public static string regularGrammar {
            get {
                return ResourceManager.GetString("regularGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler/regularGrammar.txt.
        /// </summary>
        public static string regularGrammar_txt {
            get {
                return ResourceManager.GetString("regularGrammar.txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 0
        ///&gt; 1
        ///= 2
        ///&quot; 3
        //// 1.
        /// </summary>
        public static string syntaxGrammar {
            get {
                return ResourceManager.GetString("syntaxGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler/syntaxGrammar.txt.
        /// </summary>
        public static string syntaxGrammar_txt {
            get {
                return ResourceManager.GetString("syntaxGrammar.txt", resourceCulture);
            }
        }
    }
}
